apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: rpc-network-partition
  namespace: audit-ledger
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - audit-ledger
    labelSelectors:
      app.kubernetes.io/name: stellar-rpc-primary
  direction: to
  target:
    selector:
      namespaces:
        - audit-ledger
      labelSelectors:
        app.kubernetes.io/name: audit-ledger-api
  duration: 60s
