#!/usr/bin/env python3
"""
generate_docs.py — Generate docs/storage-layout.md from a snapshot JSON.

Usage:
    python3 generate_docs.py --snapshot snapshots/current.json \
                             --output docs/storage-layout.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def format_fields(fields: list[dict]) -> str:
    """Format a fields list as a compact string for the table."""
    if not fields:
        return "—"
    parts = []
    for f in sorted(fields, key=lambda x: x.get("position", 0)):
        name = f.get("name")
        typ = f.get("type", "?")
        if name:
            parts.append(f"{name}: {typ}")
        else:
            parts.append(typ)
    return ", ".join(parts)


def generate_markdown(snapshot: dict, snapshot_path: str) -> str:
    """Generate the full Markdown document from a snapshot dict."""
    contract = snapshot.get("contract", "Unknown")
    generated_at = snapshot.get("generated_at", "unknown")
    git_commit = snapshot.get("git_commit", "unknown")
    rust_toolchain = snapshot.get("rust_toolchain", "unknown")
    variants: list[dict] = snapshot.get("variants", [])

    # Sort by ordinal
    variants_sorted = sorted(variants, key=lambda v: v.get("ordinal", 0))

    total = len(variants_sorted)
    tombstone_count = sum(1 for v in variants_sorted if v.get("tombstone", False))
    active_count = total - tombstone_count

    lines = []

    # Header
    lines.append(f"# Storage Layout — {contract}")
    lines.append("")
    lines.append(f"> Auto-generated from `{snapshot_path}`.")
    lines.append("> Do not edit manually — run `make storage-layout` to regenerate.")
    lines.append("")
    lines.append(f"**Contract:** {contract}  ")
    lines.append(f"**Generated:** {generated_at}  ")
    lines.append(f"**Git commit:** {git_commit}  ")
    if rust_toolchain and rust_toolchain != "unknown":
        lines.append(f"**Rust toolchain:** {rust_toolchain}  ")
    lines.append("")

    # DataKey Variants table
    lines.append("## DataKey Variants")
    lines.append("")
    lines.append("| Ordinal | Variant | Kind | Fields | Tombstone | Description |")
    lines.append("|---------|---------|------|--------|-----------|-------------|")

    for v in variants_sorted:
        ordinal = v.get("ordinal", "?")
        name = v.get("name", "?")
        kind = v.get("kind", "unit")
        fields_str = format_fields(v.get("fields", []))
        tombstone = "Yes" if v.get("tombstone", False) else "No"
        comment = v.get("comment", "").replace("|", "\\|").replace("\n", " ")
        if not comment:
            comment = "—"
        lines.append(f"| {ordinal} | {name} | {kind} | {fields_str} | {tombstone} | {comment} |")

    lines.append("")

    # Statistics
    lines.append("## Statistics")
    lines.append("")
    lines.append(f"- Total variants: {total}")
    lines.append(f"- Active variants: {active_count}")
    lines.append(f"- Tombstone variants: {tombstone_count}")
    lines.append("")

    # Schema version note
    schema_version = snapshot.get("version", 1)
    lines.append(f"## Metadata")
    lines.append("")
    lines.append(f"- Schema version: {schema_version}")
    if rust_toolchain:
        lines.append(f"- Rust toolchain: {rust_toolchain}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "*This document is automatically regenerated by `scripts/storage-layout/check_layout.sh`. "
        "To update, run:*"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("./scripts/storage-layout/check_layout.sh --update-baseline")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Markdown storage layout reference from a snapshot JSON."
    )
    parser.add_argument(
        "--snapshot",
        required=True,
        help="Path to the snapshot JSON file.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output Markdown file path.",
    )
    args = parser.parse_args()

    snapshot_path = Path(args.snapshot)
    if not snapshot_path.exists():
        print(f"ERROR: Snapshot not found: {snapshot_path}", file=sys.stderr)
        return 1

    try:
        with snapshot_path.open(encoding="utf-8") as f:
            snapshot = json.load(f)
    except Exception as e:
        print(f"ERROR: Could not load snapshot: {e}", file=sys.stderr)
        return 1

    markdown = generate_markdown(snapshot, str(snapshot_path))

    output_path = Path(args.output)
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(markdown, encoding="utf-8")
    except OSError as e:
        print(f"ERROR: Could not write output: {e}", file=sys.stderr)
        return 1

    variant_count = len(snapshot.get("variants", []))
    print(f"Generated {output_path} ({variant_count} variants)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
