//! Storage layout snapshot — auto-generated, do not edit manually.
//!
//! Run `scripts/storage-layout/check_layout.sh --update-baseline` to refresh.
//! This module provides compile-time access to the current layout for tests.

/// JSON snapshot of the DataKey storage layout.
/// Generated by `scripts/storage-layout/extract_layout.py`.
pub const LAYOUT_SNAPSHOT_JSON: &str =
    include_str!("../scripts/storage-layout/snapshots/current.json");

/// Semantic version of this layout snapshot format.
pub const LAYOUT_SCHEMA_VERSION: u32 = 1;

/// Total number of DataKey variants in the current layout (including tombstones).
pub const DATAKEY_VARIANT_COUNT: u32 = 79; // update when variants are added

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn layout_snapshot_is_valid_json() {
        // Parse the embedded JSON to catch formatting errors at compile-test time.
        // Uses only std — no serde dependency needed here.
        let json = LAYOUT_SNAPSHOT_JSON;
        assert!(!json.is_empty(), "layout snapshot must not be empty");
        // Verify top-level keys are present
        assert!(
            json.contains("\"variants\""),
            "snapshot must have variants key"
        );
        assert!(
            json.contains("\"version\""),
            "snapshot must have version key"
        );
        assert!(
            json.contains("\"contract\""),
            "snapshot must have contract key"
        );
    }

    #[test]
    fn layout_snapshot_has_expected_variant_count() {
        // Count occurrences of `"ordinal"` as a proxy for variant count.
        let count = LAYOUT_SNAPSHOT_JSON.matches("\"ordinal\"").count() as u32;
        assert_eq!(
            count, DATAKEY_VARIANT_COUNT,
            "variant count mismatch: update DATAKEY_VARIANT_COUNT constant"
        );
    }

    #[test]
    fn no_duplicate_ordinals_in_snapshot() {
        // Naive ordinal extraction: find all `"ordinal": N` patterns.
        let mut ordinals: HashSet<u32> = HashSet::new();
        let mut remaining = LAYOUT_SNAPSHOT_JSON;
        while let Some(pos) = remaining.find("\"ordinal\":") {
            remaining = &remaining[pos + 10..];
            let trimmed = remaining.trim_start_matches(|c: char| c.is_whitespace());
            let end = trimmed
                .find(|c: char| !c.is_ascii_digit())
                .unwrap_or(trimmed.len());
            if !trimmed[..end].is_empty() {
                if let Ok(n) = trimmed[..end].parse::<u32>() {
                    assert!(
                        ordinals.insert(n),
                        "duplicate ordinal {n} in layout snapshot"
                    );
                }
            }
        }
        assert!(!ordinals.is_empty(), "no ordinals found in snapshot");
    }

    #[test]
    fn all_known_variants_present_in_snapshot() {
        let must_contain = [
            "\"Owner\"",
            "\"Config\"",
            "\"GlobalMaxLogs\"",
            "\"Paused\"",
            "\"EventData\"",
            "\"EventOrder\"",
            "\"RuntimeState\"",
            "\"ContractVersion\"",
            "\"PauseConfig\"",
            "\"WebhookRegistrations\"",
        ];
        for name in &must_contain {
            assert!(
                LAYOUT_SNAPSHOT_JSON.contains(*name),
                "variant {name} missing from layout snapshot"
            );
        }
    }

    #[test]
    fn layout_schema_version_is_one() {
        assert_eq!(LAYOUT_SCHEMA_VERSION, 1);
    }

    #[test]
    fn datakey_variant_count_is_positive() {
        assert!(DATAKEY_VARIANT_COUNT > 0);
    }
}
